---
# Setup/install tasks.
# - name: Include Red Hat setup tasks
#   ansible.builtin.include_tasks: setup-redhat.yml
#   when: ansible_os_family == 'RedHat'

- name: Include Debian setup tasks
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure rabbitmq is started and enabled (if configured).
  ansible.builtin.service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"
