---
- name: Add RabbitMQ GPG keys.
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://packagecloud.io/gpg.key"
    - "https://packagecloud.io/rabbitmq/erlang/gpgkey"
    - "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey"
    - "https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc"

- name: Download erlang package.
  ansible.builtin.get_url:
    url: "{{ erlang_rpm_url }}"
    dest: "/tmp/{{ erlang_rpm }}"
    mode: '0644'

- name: Ensure erlang is installed.
  ansible.builtin.yum:
    name: "/tmp/{{ rabbitmq_rpm }}"
    state: "present"

- name: Download RabbitMQ package.
  ansible.builtin.get_url:
    url: "{{ rabbitmq_rpm_url }}"
    dest: "/tmp/{{ rabbitmq_rpm }}"
    mode: '0644'

- name: Ensure RabbitMQ is installed.
  ansible.builtin.yum:
    name: "/tmp/{{ rabbitmq_rpm }}"
    state: "present"
